version: 2

jobs:
  linux:
    docker:
      - image: swift:5.0
    steps:
      - checkout
      - run: swift build -v
      - run: swift test -v
  linux-release:
    docker:
      - image: swift:5.0
    steps:
      - checkout
      - run: swift build -c release

workflows:
  version: 2
  tests:
    jobs:
      - linux
      - linux-release
